/**
 * Portfolio Export Service
 * Packages generated portfolio HTML into a downloadable ZIP file.
 * Place at: backend/services/portfolioExport.service.js
 *
 * Install dependency:
 *   npm install archiver
 */

const archiver = require("archiver");
console.log("ARCHIVER TYPE =", typeof archiver);
console.log("ARCHIVER =", archiver);
const { Readable, PassThrough } = require("stream");
const { renderPortfolioHTML } = require("./portfolioTemplate.service");

/**
 * Exports a portfolio as a self-contained ZIP archive.
 * The ZIP contains:
 *   ├── index.html       (standalone portfolio page)
 *   └── README.txt       (deployment instructions)
 *
 * @param {Object} portfolioData  - Normalized portfolio data
 * @param {string} template       - Template ID
 * @returns {Promise<{ zipBuffer: Buffer, fileName: string }>}
 */
const exportPortfolioAsZip =
async (
  portfolioData,
  template,
  html
) => {
  // ── Render the HTML ───────────────────────────
  const htmlContent =
html ||
await renderPortfolioHTML(
  portfolioData,
  template
);
const name = "portfolio";
 

  const fileName = `${name}-portfolio-${template}.zip`;

  // ── Build README ──────────────────────────────
 const readme =
buildReadme(
  "Portfolio User",
  template || "cyberpunk"
);

  // ── Create ZIP in memory ──────────────────────
  const zipBuffer = await buildZip({
    "index.html": htmlContent,
    "README.txt": readme,
  });

  return { zipBuffer, fileName };
};

// ──────────────────────────────────────────────
// ZIP builder using archiver (streaming → Buffer)
// ──────────────────────────────────────────────

/**
 * Creates a ZIP buffer from a flat map of { filename: content } pairs.
 * @param {Object} files - { 'index.html': '<html>...</html>', ... }
 * @returns {Promise<Buffer>}
 */
const buildZip = (files) =>
  new Promise((resolve, reject) => {
    const archive = archiver("zip", { zlib: { level: 9 } });
    const chunks = [];

    archive.on("data",  (chunk) => chunks.push(chunk));
    archive.on("end",   () => resolve(Buffer.concat(chunks)));
    archive.on("error", (err) => reject(err));

    for (const [filename, content] of Object.entries(files)) {
      archive.append(
        Buffer.isBuffer(content) ? content : Buffer.from(content, "utf8"),
        { name: filename }
      );
    }

    archive.finalize();
  });

// ──────────────────────────────────────────────
// README content
// ──────────────────────────────────────────────

const buildReadme = (name, template) => `
Portfolio of ${name}
Generated by ResumeIQ AI | Template: ${template.toUpperCase()}
Generated: ${new Date().toUTCString()}

═══════════════════════════════════════
HOW TO USE YOUR PORTFOLIO
═══════════════════════════════════════

OPTION 1 — Open Locally
  1. Extract this ZIP file
  2. Open index.html in any modern browser
  3. No internet required — fonts load from Google CDN

OPTION 2 — Deploy to GitHub Pages (FREE)
  1. Create a GitHub repository named: ${name || "yourname"}.github.io
  2. Upload index.html to the repo
  3. Go to Settings → Pages → Deploy from branch (main)
  4. Your portfolio is live at: https://${name || "yourname"}.github.io

OPTION 3 — Deploy to Netlify (FREE)
  1. Go to https://netlify.com/drop
  2. Drag and drop the index.html file
  3. Your portfolio is instantly live!

OPTION 4 — Deploy to Vercel (FREE)
  1. Install Vercel CLI: npm i -g vercel
  2. Run: vercel --prod
  3. Follow the prompts

═══════════════════════════════════════
CUSTOMIZATION
═══════════════════════════════════════
  - Edit index.html directly to change content
  - CSS variables at top of <style> control colors:
      --primary: your main color
      --accent:  your accent color
  - Fonts: Uses Google Fonts (Inter, Orbitron, JetBrains Mono)

═══════════════════════════════════════
Generated by ResumeIQ AI Platform
https://resumeiq.ai
═══════════════════════════════════════
`.trim();

module.exports = { exportPortfolioAsZip };