const STATUS = {
  // 2xx Success
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  // 3xx Redirection
  MOVED_PERMANENTLY: 301,
  NOT_MODIFIED: 304,

  // 4xx Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  GONE: 410,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  PAYLOAD_TOO_LARGE: 413,

  // 5xx Server Errors
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
};

const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  FORBIDDEN: "FORBIDDEN",
  AUTH_FAILED: "AUTH_FAILED",
  AUTH_UNAVAILABLE: "AUTH_UNAVAILABLE",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_JSON: "INVALID_JSON",
  INVALID_ID: "INVALID_ID",

  // Upload
  NO_FILE: "NO_FILE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  INVALID_EXTENSION: "INVALID_EXTENSION",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  UPLOAD_ERROR: "UPLOAD_ERROR",

  // AI
  AI_RATE_LIMIT: "AI_RATE_LIMIT",
  AI_UNAVAILABLE: "AI_UNAVAILABLE",
  AI_PARSE_ERROR: "AI_PARSE_ERROR",
  GENERATION_FAILED: "GENERATION_FAILED",
  ANSWER_TOO_SHORT: "ANSWER_TOO_SHORT",

  // Resource
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_KEY: "DUPLICATE_KEY",
  CONFLICT: "CONFLICT",
  PLAN_UPGRADE_REQUIRED: "PLAN_UPGRADE_REQUIRED",

  // Server
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UPSTREAM_ERROR: "UPSTREAM_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  PARSE_ERROR: "PARSE_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
};

const SUCCESS_MESSAGES = {
  RESUME_UPLOADED: "Resume uploaded and parsed successfully",
  ANALYSIS_COMPLETE: "Analysis completed successfully",
  SKILLS_EXTRACTED: "Skills extracted successfully",
  RECOMMENDATIONS_GENERATED: "Skill recommendations generated successfully",
  JOBS_MATCHED: "Jobs matched successfully",
  QUESTIONS_GENERATED: "Interview questions generated successfully",
  ANSWER_EVALUATED: "Answer evaluated successfully",
  SUMMARY_GENERATED: "Professional summary generated successfully",
  PROFILE_UPDATED: "Profile updated successfully",
  PASSWORD_CHANGED: "Password changed successfully",
  CHAT_RESPONSE: "Response generated successfully",
  RESUME_DELETED: "Resume deleted successfully",
  RESUME_SAVED: "Resume builder draft saved",
};

const HTTP_METHODS = {
  GET: "GET",
  POST: "POST",
  PUT: "PUT",
  PATCH: "PATCH",
  DELETE: "DELETE",
  OPTIONS: "OPTIONS",
};

module.exports = { STATUS, ERROR_CODES, SUCCESS_MESSAGES, HTTP_METHODS };